In [14]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split

In [15]:
digits = load_digits()
x_train, x_test, y_train, y_test = train_test_split(digits.data,digits.target,test_size=0.4)

In [16]:
# Models
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC

In [17]:
linr = LinearRegression()
linr.fit(x_train,y_train)
linr.score(x_test,y_test)


0.5678157647564512

In [18]:
logr = LogisticRegression()
logr.fit(x_train,y_train)
logr.score(x_test,y_test)

C:\Users\LENOVO\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.96105702364395

In [19]:
dectree = DecisionTreeClassifier()
dectree.fit(x_train,y_train)
dectree.score(x_test,y_test)

0.8386648122392212

In [20]:
ran = RandomForestClassifier()
ran.fit(x_train,y_train)
ran.score(x_test,y_test)

0.9777468706536857

In [21]:
sup = SVC()
sup.fit(x_train,y_train)
sup.score(x_test,y_test)

0.9902642559109874

In [22]:
from sklearn.model_selection import KFold

In [23]:
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [25]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [26]:
def get_score(model,x_train,x_test,y_train,y_test):
    model.fit(x_train,y_train)
    return model.score(x_test,y_test)

In [27]:
get_score(SVC(),x_train,x_test,y_train,y_test)

0.9902642559109874

In [28]:
get_score(RandomForestClassifier(),x_train,x_test,y_train,y_test)

0.9735744089012517

In [29]:
get_score(DecisionTreeClassifier(),x_train,x_test,y_train,y_test)

0.827538247566064

In [30]:
get_score(LogisticRegression(),x_train,x_test,y_train,y_test)

C:\Users\LENOVO\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.96105702364395

In [31]:
get_score(LinearRegression(),x_train,x_test,y_train,y_test)

0.5678157647564512

In [32]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

In [ ]:
score_linr = []
score_logr = []
score_dectree = []
score_ran = []
score_svm = []
